DECLARE
CURSOR MAT IS 
SELECT CODE, LIBELLE
FROM MODULE
WHERE CODE NOT IN (SELECT CODEPERE FROM MODULE WHERE CODEPERE IS NOT NULL);
PASMAT EXCEPTION;
TROUVER BOOLEAN := FALSE;
BEGIN
FOR M IN MAT
LOOP
TROUVER := TRUE;
DBMS_OUTPUT.PUT_LINE(M.CODE||''||M.LIBELLE);
END LOOP;
IF NOT TROUVER THEN RAISE PASMAT;END IF;
EXCEPTION
WHEN PASMAT THEN 
DBMS_OUTPUT.PUT_LINE('non');
END;

