/*Q1*/
SELECT column_name 
FROM USER_TAB_COLS
  WHERE TABLE_NAME = 'PROF';
  

/*Q2*/
SELECT OBJECT_NAME 
  FROM USER_OBJECTS
  WHERE OBJECT_TYPE = 'FUNCTION';

/*Q3*/
SELECT CONSTRAINT_NAME 
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'C';

/*Q4*/

SELECT C.CONSTRAINT_NAME
FROM USER_CONSTRAINTS C JOIN USER_TAB_COLUMNS S 
ON C.TABLE_NAME = S.TABLE_NAME
WHERE S.DATA_TYPE = 'NUMBER';


/*Q5*/

SELECT C.CONSTRAINT_NAME,S.COLUMN_NAME
FROM USER_CONSTRAINTS C JOIN USER_TAB_COLUMNS S 
ON C.TABLE_NAME = S.TABLE_NAME
WHERE S.DATA_TYPE = 'NUMBER';

/*Q6*/

SELECT C.CONSTRAINT_NAME,S.COLUMN_NAME, S.DATA_TYPE
FROM USER_CONSTRAINTS C JOIN USER_TAB_COLUMNS S 
ON C.TABLE_NAME = S.TABLE_NAME
WHERE S.DATA_TYPE = 'NUMBER';


/*Q7*/

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE, SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'C';

/*Q8*/

/*Q9*/

/*Q10*/

CREATE OR REPLACE VIEW prof_info2 AS
SELECT P.NOM_PROF, P.NUM_PROF
FROM PROF P JOIN ENSEIGNT E ON P.NUM_PROF = E.NUM_PROF JOIN ETUDIANT A ON E.NUM_ET = A.NUM_ET
WHERE A.ANNEE = '2';

SELECT * 
FROM PROF_INFO2;

/*Q11*/

CREATE OR REPLACE VIEW DIS AS
SELECT *
FROM MODULE 
WHERE DISCIPLINE IN ('INFORMATIQUE','MATH','GESTION')
WITH CHECK OPTION;

INSERT INTO DIS(CODE, DISCIPLINE)
VALUES('99','SPORT');
 
/*Q12*/

CREATE OR REPLACE VIEW FOO AS
SELECT DISTINCT(P.NOM_PROF)
FROM PROF P JOIN ENSEIGNT E ON 
P.NUM_PROF = E.NUM_PROF JOIN 
MODULE M ON E.CODE = M.CODE
WHERE P.MAT_SPEC = M.CODE AND P.NUM_PROF = M.RESP
WITH CHECK OPTION;

CREATE OR REPLACE VIEW MAT AS
SELECT * FROM MODULE MO
WHERE RESP IN (SELECT NUM_PROF FROM ENSEIGNT E WHERE MO.CODE = E.CODE)
WITH CHECK OPTION;

/*Q13*/

CREATE OR REPLACE VIEW FOOL AS
SELECT * FROM ENSEIGNT E
WHERE E.CODE IN (SELECT CODE FROM MODULE) AND E.NUM_ET IN (SELECT NUM_ET FROM ETUDIANT) AND E.NUM_PROF IN (SELECT NUM_PROF FROM PROF)
WITH CHECK OPTION;

INSERT INTO FOOL
VALUES ('SPO',212,12);

/*Q14*/

CREATE OR REPLACE VIEW FAA AS 
SELECT * FROM MODULE M
WHERE M.CODE IN 







